#!/bin/bash
# OTA Test Harness Build Setup
# Matter SDK v1.5.1.0
# Platform: Linux x86_64

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    cat <<EOF
Usage: $0 [--version <N>]

Builds chip-ota-requestor-app twice:
  - version N   → \$MATTER_BUILD_DIR      (the running end node)
  - version N+1 → \$MATTER_OTA_BUILD_DIR  (payload for the OTA images)
plus chip-ota-provider-app and chip-tool.

Options:
  --version <N>   Current software version (default: 10)

Example:
  $0 --version 10    # builds v10 requestor and v11 OTA requestor
EOF
    exit 1
}

VERSION_ARG=10
while [[ $# -gt 0 ]]; do
    case $1 in
        --version|-v)
            [ -z "${2:-}" ] && usage
            VERSION_ARG="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

if ! [[ "$VERSION_ARG" =~ ^[0-9]+$ ]]; then
    echo "ERROR: --version must be a non-negative integer (got: $VERSION_ARG)"
    exit 1
fi

# Load central configuration
source "$SCRIPT_DIR/setup.sh"

# Command-line version overrides any previously recorded build-version.env
CURRENT_VERSION="$VERSION_ARG"
OTA_VERSION=$((CURRENT_VERSION + 1))

SDK_ROOT="$MATTER_SDK_ROOT"
BUILD_DIR="$MATTER_BUILD_DIR"
OTA_BUILD_DIR="$MATTER_OTA_BUILD_DIR"

echo "=================================================="
echo "Matter OTA Test Harness - Build Setup"
echo "=================================================="
echo "SDK Location: $SDK_ROOT"
echo "Build Directory: $BUILD_DIR"
echo "OTA Build Directory: $OTA_BUILD_DIR"
echo "Current Version: $CURRENT_VERSION"
echo "OTA Version: $OTA_VERSION"
echo ""

# Check SDK exists
if [ ! -d "$SDK_ROOT" ]; then
    echo "ERROR: Matter SDK not found at: $SDK_ROOT"
    echo ""
    echo "Either:"
    echo "  1. Set MATTER_SDK_ROOT to your SDK location:"
    echo "     export MATTER_SDK_ROOT=/path/to/connectedhomeip"
    echo "  2. Clone the SDK:"
    echo "     git clone --depth 1 --branch v1.5.1.0 https://github.com/project-chip/connectedhomeip.git"
    exit 1
fi

# Check dependencies
echo "Checking dependencies..."
MISSING_DEPS=()

command -v python3 >/dev/null || MISSING_DEPS+=("python3")
command -v ninja >/dev/null || MISSING_DEPS+=("ninja-build")
command -v pkg-config >/dev/null || MISSING_DEPS+=("pkg-config")
command -v git >/dev/null || MISSING_DEPS+=("git")
command -v g++ >/dev/null || MISSING_DEPS+=("g++")

if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
    echo "ERROR: Missing dependencies: ${MISSING_DEPS[*]}"
    echo "Install with: sudo apt-get install ${MISSING_DEPS[*]}"
    exit 1
fi
echo "✓ All dependencies found"
echo ""

# Bootstrap SDK environment if needed
cd "$SDK_ROOT"
if [ ! -d ".environment" ]; then
    echo "Bootstrapping SDK environment (first time only, ~5 minutes)..."
    python3 scripts/checkout_submodules.py --shallow --platform linux
    bash scripts/build/gn_bootstrap.sh
    echo "✓ Bootstrap complete"
fi

# Activate environment
echo "Activating Matter environment..."
source scripts/activate.sh

# gn args that bake the software version into the requestor binary.
# The string arg needs embedded quotes since gn_build_example.sh joins args into --args.
version_args() {
    local v=$1
    echo "chip_device_config_device_software_version=$v"
    echo "chip_device_config_device_software_version_string=\"$v.0\""
}

# Build apps using SDK's build script
echo ""
echo "Building OTA requestor app (version $CURRENT_VERSION)..."
mapfile -t CURRENT_ARGS < <(version_args "$CURRENT_VERSION")
bash scripts/examples/gn_build_example.sh \
    examples/ota-requestor-app/linux \
    "$BUILD_DIR" \
    "is_debug=false" \
    "${CURRENT_ARGS[@]}"

echo ""
echo "Building OTA requestor app (version $OTA_VERSION, OTA payload)..."
mapfile -t OTA_ARGS < <(version_args "$OTA_VERSION")
bash scripts/examples/gn_build_example.sh \
    examples/ota-requestor-app/linux \
    "$OTA_BUILD_DIR" \
    "is_debug=false" \
    "${OTA_ARGS[@]}"

echo ""
echo "Building OTA provider app..."
bash scripts/examples/gn_build_example.sh \
    examples/ota-provider-app/linux \
    "$BUILD_DIR" \
    "is_debug=false"

echo ""
echo "Building chip-tool..."
bash scripts/examples/gn_build_example.sh \
    examples/chip-tool \
    "$BUILD_DIR" \
    "is_debug=false"

# Verify binaries
echo ""
echo "Verifying binaries..."
ALL_OK=true
for bin in chip-ota-requestor-app chip-ota-provider-app chip-tool; do
    if [ -f "$BUILD_DIR/$bin" ]; then
        echo "  ✓ $bin"
    else
        echo "  ✗ $bin - MISSING"
        ALL_OK=false
    fi
done
if [ -f "$OTA_BUILD_DIR/chip-ota-requestor-app" ]; then
    echo "  ✓ chip-ota-requestor-app (v$OTA_VERSION, $OTA_BUILD_DIR)"
else
    echo "  ✗ chip-ota-requestor-app (v$OTA_VERSION) - MISSING"
    ALL_OK=false
fi

if [ "$ALL_OK" = true ]; then
    # Record versions for make-ota-images.sh / run-requestor.sh (read via setup.sh)
    cat > "$SCRIPT_DIR/build-version.env" <<EOF
# Generated by build-setup.sh — do not edit
CURRENT_VERSION=$CURRENT_VERSION
OTA_VERSION=$OTA_VERSION
EOF

    echo ""
    echo "=================================================="
    echo "Build complete!"
    echo "=================================================="
    echo "Binaries: $BUILD_DIR (v$CURRENT_VERSION)"
    echo "OTA payload: $OTA_BUILD_DIR/chip-ota-requestor-app (v$OTA_VERSION)"
    echo "Versions recorded in: $SCRIPT_DIR/build-version.env"
    echo ""
    echo "Next steps:"
    echo "  ./scripts/make-ota-images.sh"
    echo "  ./scripts/start-ota-end-node.sh start 1"
    exit 0
else
    echo ""
    echo "ERROR: Build failed - some binaries missing"
    exit 1
fi
